curl http://localhost:8080/pizza 

###

curl -X POST -H "Content-Type: application/json" http://localhost:8080/pizza -d '{"name": "Hawaii"}'

###

curl http://localhost:8080/feature

###

curl -X PUT -H "Content-Type: application/json" http://localhost:8080/feature -d '{"name": "list-pizza-hawaii", "state": true}'
